DATASET: MELD
model_checkpoint: roberta-large
speaker_mode: null
num_past_utterances: 1000
num_future_utterances: 1000
BATCH_SIZE: 4
HP_ONLY_UPTO: 103
NUM_TRAIN_EPOCHS: 5
WEIGHT_DECAY: 0.01
WARMUP_RATIO: 0.2
HP_N_TRIALS: 5
SEEDS:
- 0
- 1
- 2
- 3
- 4