DATASET: MELD
model_checkpoint: roberta-base
speaker_mode: null
num_past_utterances: 0
num_future_utterances: 0
BATCH_SIZE: 1
HP_ONLY_UPTO: 10
NUM_TRAIN_EPOCHS: 5
WEIGHT_DECAY: 0.01
WARMUP_RATIO: 0.2
HP_N_TRIALS: 1
SEEDS:
- 0
- 1
- 2
- 3
- 4
