DATASET: MELD_IEMOCAP
model_checkpoint: roberta-base
speaker_mode: null
num_past_utterances: 0
num_future_utterances: 0
BATCH_SIZE: 16
HP_ONLY_UPTO: 20
NUM_TRAIN_EPOCHS: 20
WEIGHT_DECAY: 0.01
WARMUP_RATIO: 0.2
HP_N_TRIALS: 10
SEEDS:
- 42