id:                             context_aware_multimodal_fusion
pretrained:                     Null
model:
    name:                       ContextAwareModel
    args:
        num_classes:            7
        AUDIO_FEAT_DIM:         1280
        TEXT_FEAT_DIM:          1024
        EMB_DIM:                256
        use_concat:             False
optimizer:
    name:                       Adam
    args:
        lr:                     0.00003
loss:
    name:                       FocalLoss
    args:                       
        alpha:                  0.75
        gamma:                  3
        reduce:                 True
metric:
    -   name:                   F1Weighted
        args:                   Null
scheduler:
    name:                       StepLR
    args:
        step_size:              1
        gamma:                  0.2
        last_epoch:             -1
dataset:            
    train:
        name:                   ContextAwareDataset
        args:    
            csv_path:           data/raw-audios-wav/train.csv
            audio_feat_dir:     Datasets/MELD/audio-features/train/
            text_feat_dir:      Datasets/MELD/text-features/train/
            ordered_json_list:  Datasets/MELD/utterance-ordered.json
            num_utt:            5
            dataset:            train
        loader:
            name: DataLoader
            args:
                batch_size:     8
                shuffle:        True
                drop_last:      True
    val:
        name:                   ContextAwareDataset
        args:
            csv_path:           data/raw-audios-wav/val.csv
            audio_feat_dir:     Datasets/MELD/audio-features/val/
            text_feat_dir:      Datasets/MELD/text-features/val/
            ordered_json_list:  Datasets/MELD/utterance-ordered.json
            num_utt:            5
            dataset:            val
        loader:
            name: DataLoader
            args:
                batch_size:     8
                shuffle:        True
                drop_last:      True
 
trainer: 
    nepochs: 10
    val_step: 1
    log_step: 1