id:                             audio_effnet_b0
pretrained:                     Null
model:
    name:                       BaseTimmModel
    args:
        name:                   tf_efficientnet_b0_ns
        num_classes:            7
        freeze_backbone:        False
        from_pretrained:        True 
optimizer:
    name:                       Adam
    args:
        lr:                     0.00001
loss:
    name:                       FocalLoss
    args:                       Null
metric:
    -   name:                   F1Weighted
        args:                   Null
scheduler:
    name:                       StepLR
    args:
        step_size:              3
        gamma:                  0.2
        last_epoch:             -1  
dataset:            
    train:
        name:                   AudioDataset
        args:
            data_dir:           data/MELD/raw-audios-wav/train/        
            csv_path:           data/MELD/raw-audios/train.csv
            format:             .wav
            sr:                 22050
            duration:           8
            n_mels:             128
            is_train:           True  
        loader:
            name: DataLoader
            args:
                batch_size:     4
                shuffle:        True
                drop_last:      True
    val:
        name:                   AudioDataset
        args:
            data_dir:           data/MELD/raw-audios-wav/val/        
            csv_path:           data/MELD/raw-audios/val.csv
            format:             .wav
            sr:                 22050
            duration:           8
            n_mels:             128
            is_train:           False
        loader:
            name: DataLoader
            args:
                batch_size:     4
                shuffle:        True

trainer: 
    nepochs: 10
    val_step: 1
    log_step: 1