id:                             single_utterance_multimodal_fusion
pretrained:                     Null
model:
    name:                       FusionModel
    args:
        num_classes:            7
        AUDIO_FEAT_DIM:         1280
        TEXT_FEAT_DIM:          1024
        EMB_DIM:                256
        use_concat:             False
        single_utt:             True
optimizer:
    name:                       Adam
    args:
        lr:                     0.00003
loss:
    name:                       FocalLoss
    args:                       
        alpha:                  0.75
        gamma:                  2
        reduce:                 True
metric:
    -   name:                   F1Weighted
        args:                   Null
scheduler:
    name:                       StepLR
    args:
        step_size:              2
        gamma:                  0.2
        last_epoch:             -1
dataset:            
    train:
        name:                   AudioTextFeatureVectorDataset
        args:    
            csv_path:           data/raw-audios-wav/train.csv
            audio_feat_dir:     Datasets/MELD/audio-features/train/
            text_feat_dir:      Datasets/MELD/text-features/train/
        loader:
            name: DataLoader
            args:
                batch_size:     16
                shuffle:        True
                drop_last:      True
    val:
        name:                   AudioTextFeatureVectorDataset
        args:
            csv_path:           data/raw-audios-wav/val.csv
            audio_feat_dir:     Datasets/MELD/audio-features/val/
            text_feat_dir:      Datasets/MELD/text-features/val/
        loader:
            name: DataLoader
            args:
                batch_size:     16
                shuffle:        True
                drop_last:      True
 
trainer: 
    nepochs: 4
    val_step: 1
    log_step: 1