id:                             single_utterance_multimodal_fusion
pretrained:                     Null
model:
    name:                       FusionModel
    args:
        num_classes:            7
optimizer:
    name:                       Adam
    args:
        lr:                     0.00001
loss:
    name:                       FocalLoss
    args:                       
        alpha:                  0.75
        gamma:                  3
        reduce:                 True
metric:
    -   name:                   F1Weighted
        args:                   Null
scheduler:
    name:                       ReduceLROnPlateau
    args:
        factor:                 0.1
        patience:               5
dataset:            
    train:
        name:                   AudioTextFeatureVectorDataset
        args:    
            csv_path:           data/raw-audios-wav/train.csv
            audio_feat_dir:     Datasets/MELD/audio-features/train/
            text_feat_dir:      Datasets/MELD/text-features/train/
        loader:
            name: DataLoader
            args:
                batch_size:     8
                shuffle:        True
                drop_last:      True
    val:
        name:                   AudioTextFeatureVectorDataset
        args:
            csv_path:           data/raw-audios-wav/val.csv
            audio_feat_dir:     Datasets/MELD/audio-features/val/
            text_feat_dir:      Datasets/MELD/text-features/val/
        loader:
            name: DataLoader
            args:
                batch_size:     8
                shuffle:        True
                drop_last:      True
 
trainer: 
    nepochs: 20
    val_step: 1
    log_step: 1