id: timesformer
pretrained: Null
model:
  name: TimeSformer
  args:
    dim: 512
    image_size: 112
    patch_size: 8
    num_frames: 8
    num_classes: 7
    depth: 12
    heads: 8
    dim_head: 64
    attn_dropout: 0.1
    ff_dropout: 0.1
optimizer:
  name: Adam
  args:
    lr: 0.001
loss:
  name: CrossEntropyLoss
  args: Null
metric:
  - name: Accuracy
    args: Null
scheduler:
  name: StepLR
  args:
    step_size: 3
    gamma: 0.2
    last_epoch: -1
dataset:
  train:
    name: CAER
    args:
      balancing: over
      label_path: /home/tkm290/repos/erc/Datasets/CAER/labels.json
      videos_dir: /home/tkm290/repos/erc/Datasets/CAER/face-videos/train/
      # audios_dir: /home/tkm290/repos/erc/Datasets/CAER/raw-audios/train/
      # texts_dir: /home/tkm290/repos/erc/Datasets/CAER/raw-texts/train/
      # faces_dir: 
      every_N: 16
      num_frames: 8
      image_size: 112
      datatype: train
    loader:
      name: DataLoader
      args:
        batch_size: 4
        shuffle: True
        drop_last: False
  val:
    name: CAER
    args:
      label_path: /home/tkm290/repos/erc/Datasets/CAER/labels.json
      videos_dir: /home/tkm290/repos/erc/Datasets/CAER/face-videos/val/
      # audios_dir: /home/tkm290/repos/erc/Datasets/CAER/raw-audios/val/
      # texts_dir: /home/tkm290/repos/erc/Datasets/CAER/raw-texts/val/
      # faces_dir: 
      every_N: 16
      num_frames: 8
      image_size: 112
      datatype: val
    loader:
      name: DataLoader
      args:
        batch_size: 4
        shuffle: True

trainer:
  nepochs: 10
  val_step: 1
  log_step: 1
